#pragma once
// Supported consumer entry point. Solver caches, broad/narrow phase details,
// and headers not listed in docs/api.md are implementation interfaces.
#include "engine.h"
#include "physics/core/charged_particle.h"
#include "physics/core/nbody_gravity.h"
#include "physics/core/joints.h"
#include "physics/core/softbody.h"
#include "physics/core/thermal_network.h"
#include "physics/core/forces/gravity.h"
#include "physics/core/forces/drag.h"
#include "physics/core/collisions/continuous_collision.h"
#include "physics/core/fluids/dfsph_solver.h"
#include "physics/core/fluids/wcsph_solver.h"
#include "physics/core/fluids/periodic_mac_grid.h"
#include "physics/core/fluids/periodic_scalar_transport.h"
#include "physics/core/fluids/coupled_fluid_simulation.h"
#include "physics/core/state_export.h"
#include "physics/core/spatial_queries.h"
#include "physics/core/prismatic_joint.h"
#include "physics/core/wave_membrane.h"
#include "physics/core/maxwell_grid.h"
