execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result OUTPUT_VARIABLE report ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Planar interval diagnostic failed: ${error}")
endif()
if(NOT CMAKE_VERSION VERSION_LESS 3.19)
    string(JSON classification GET "${report}" classification)
    string(JSON count LENGTH "${report}" rows)
    string(JSON changed GET "${report}" productionDefaultsChanged)
    string(JSON bridge GET "${report}" worldBridge)
    if(NOT classification STREQUAL "bounded_planar_observation" OR NOT count EQUAL 6 OR changed OR bridge)
        message(FATAL_ERROR "Unexpected planar interval observation schema")
    endif()
endif()
