execute_process(COMMAND "${PROGRAM}" --quick RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Planar World benchmark failed: ${errors}")
endif()
string(JSON failures GET "${output}" executionFailures)
string(JSON count LENGTH "${output}" rows)
if(NOT failures EQUAL 0 OR NOT count EQUAL 13)
    message(FATAL_ERROR "Invalid bounded Planar World result")
endif()
foreach(index RANGE 0 12)
    string(JSON fixture GET "${output}" rows ${index} fixture)
    string(JSON steps GET "${output}" rows ${index} stepsPerPipeline)
    string(JSON selected GET "${output}" rows ${index} experimental selectedSteps)
    if(index LESS 9)
        if(NOT selected EQUAL steps)
            message(FATAL_ERROR "Expected selected World interval for ${fixture}")
        endif()
        string(JSON iterations GET "${output}" rows ${index} experimental solverIterationCountSum)
        if(NOT iterations EQUAL 0)
            message(FATAL_ERROR "Selected World interval ran iterative solve for ${fixture}")
        endif()
    endif()
    if(fixture STREQUAL "opaque_fallback")
        string(JSON calls GET "${output}" rows ${index} experimental opaqueForceCalls)
        string(JSON baselineState GET "${output}" rows ${index} baseline finalState)
        string(JSON experimentalState GET "${output}" rows ${index} experimental finalState)
        if(NOT calls EQUAL steps OR NOT selected EQUAL 0 OR NOT baselineState STREQUAL experimentalState)
            message(FATAL_ERROR "Opaque force fallback diverged or repeated load application")
        endif()
    endif()
endforeach()
